/* import React, { useState } from "react";
import WeatherService from "../../services/WeatherService";
import LocationSearch from "../LocationSearch/LocationSearch";
import CurrentWeather from "../CurrentWeather/CurrentWeather";
import "./WeatherApp.module.css";

//function to find the geo-location (latittude and longitude) based on user input and use this lat and long to get the current weather data by passing this information to the function in WeatherService.js file and then display the data in the CurrentWeather component
function WeatherApp() {
  const [weatherData, setWeatherData] = useState(null);

  const fetchWeatherData = async (location) => {
    try {
      const geoResponse = await fetch(
        // suggest an api to find the lat long based on the location
        `https://geocode.xyz/${location}?json=1`
      );
      const geoData = await geoResponse.json();
      const latitude = geoData.latt;
      const longitude = geoData.longt;
      console.log(latitude);
      console.log(longitude);

      const weatherResponse = await WeatherService.getCurrentWeather(
        latitude,
        longitude
      );
      setWeatherData(weatherResponse);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className="WeatherApp">
      <h1>Summer Weather App</h1>
      <LocationSearch onLocationSubmit={fetchWeatherData} />
      {weatherData && <CurrentWeather data={weatherData} />}
    </div>
  );
}

export default WeatherApp;
// https://geocode.xyz/${location}?json=1 */

// Manually corrected code  compared to the code generated by ChatGPT commented above
import React, { useState } from "react";
import WeatherService from "../../services/WeatherService";
import LocationSearch from "../LocationSearch/LocationSearch";
import CurrentWeather from "../CurrentWeather/CurrentWeather";
import styles from "./WeatherApp.module.css";

function WeatherApp() {
  const [weatherData, setWeatherData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchWeatherData = async (location) => {
    debugger;
    setLoading(true);
    setError("");
    try {
      const geoData = await WeatherService.getGeoLocation(location);
      const weatherResponse = await WeatherService.getCurrentWeather(
        geoData.latt,
        geoData.longt
      );
      setWeatherData(weatherResponse);
    } catch (error) {
      setError("Failed to fetch weather data. Please try again.");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.WeatherApp}>
      <h1>Summer Weather App</h1>
      <LocationSearch onLocationSubmit={fetchWeatherData} />
      {loading && <p>Loading...</p>}
      {error && <p className={styles.error}>{error}</p>}
      {weatherData && <CurrentWeather data={weatherData} />}
    </div>
  );
}

export default WeatherApp;
