/* // function to fetch current weather data from open-meteo api
async function getCurrentWeather(latitude, longitude) {
  const response = await fetch(
    `https://api.open-meteo.com/v1/current?latitude=${latitude}&longitude=${longitude}`
  );

  if (!response.ok) {
    throw new Error("Failed to fetch weather data");
  }

  const data = await response.json();
  return data;
}

export default { getCurrentWeather }; */

// Manually corrected code  compared to the code generated by ChatGPT commented above
async function getGeoLocation(location) {
  debugger;
  const response = await fetch(`https://geocode.xyz/${location}?json=1`);
  if (!response.ok) {
    throw new Error("Failed to find location");
  }
  const data = await response.json();
  if (!data.latt || !data.longt) {
    throw new Error("Location not found");
  }
  return { latitude: data.latt, longitude: data.longt };
}

async function getCurrentWeather(latitude, longitude) {
  const response = await fetch(
    `https://api.open-meteo.com/v1/current?latitude=${latitude}&longitude=${longitude}`
  );
  if (!response.ok) {
    throw new Error("Failed to fetch weather data");
  }
  return await response.json();
}

export default { getGeoLocation, getCurrentWeather };
